import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Check } from "lucide-react";
import clsx from "clsx";
const STEPS = [
    { number: 1, label: "Basic Information", subtitle: "Who are you?" },
    { number: 2, label: "Location & Constituency", subtitle: "Help us identify your jurisdiction" },
    { number: 3, label: "About You", subtitle: "Interests & profile" },
];
export default function OnboardingLayout({ currentStep, children, onContinue, onBack, continueLabel = "Continue →", }) {
    return (_jsx("div", { className: "min-h-screen bg-[var(--color-bg-page)]", children: _jsxs("div", { className: "max-w-[1400px] mx-auto px-6 py-8 md:px-10 md:py-10", children: [_jsxs("div", { className: "flex items-center justify-between mb-7", children: [_jsx("span", { className: "text-[var(--text-heading)] font-extrabold text-[var(--color-brand)]", children: "Digital Janata" }), _jsxs("span", { className: "text-xs font-bold tracking-widest text-[var(--color-text-secondary)]", children: ["STEP ", String(currentStep).padStart(2, "0"), " / 03"] })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-[280px_1fr] gap-8", children: [_jsxs("aside", { className: "bg-[var(--color-bg-surface)] rounded-xl p-7 shadow-[var(--shadow-sm)] h-fit", children: [_jsx("p", { className: "text-xs font-bold tracking-widest uppercase text-[var(--color-text-secondary)]", children: "Citizen Onboarding" }), _jsx("h2", { className: "mt-3 mb-8 text-[var(--text-display)] font-bold leading-tight text-[var(--color-text-primary)]", children: "Complete your DJ Profile" }), _jsx("div", { className: "flex flex-col gap-6", children: STEPS.map((step) => {
                                        const isDone = currentStep > step.number;
                                        const isActive = currentStep === step.number;
                                        return (_jsxs("div", { className: "flex gap-3.5 items-start", children: [_jsx("span", { className: clsx("h-[42px] w-[42px] shrink-0 rounded-full flex items-center justify-center font-bold text-sm", isDone && "bg-[var(--color-text-primary)] text-[var(--color-text-inverse)]", isActive && "bg-[var(--color-brand)] text-[var(--color-text-inverse)]", !isDone && !isActive && "bg-[var(--color-bg-subtle)] text-[var(--color-text-secondary)]"), children: isDone ? _jsx(Check, { size: 18 }) : step.number }), _jsxs("div", { className: "min-w-0", children: [_jsx("p", { className: "font-bold text-sm text-[var(--color-text-primary)]", children: isDone ? "Completed" : step.label }), _jsx("p", { className: "text-xs mt-1 text-[var(--color-text-secondary)]", children: isDone ? "" : step.subtitle })] })] }, step.number));
                                    }) }), onContinue && (_jsx("button", { onClick: onContinue, className: "mt-10 w-full py-4 rounded-xl bg-[var(--color-brand)] text-[var(--color-text-inverse)] font-bold text-sm cursor-pointer hover:opacity-90 transition-opacity", children: continueLabel })), onBack && (_jsx("button", { onClick: onBack, className: "block w-full text-center mt-4 text-sm text-[var(--color-text-secondary)] hover:underline cursor-pointer bg-transparent border-none", children: "\u2190 Back" }))] }), _jsx("main", { className: "bg-[var(--color-bg-surface)] rounded-xl p-8 md:p-10 shadow-[var(--shadow-sm)]", children: children })] })] }) }));
}
