import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { Link } from "react-router-dom";
import { ThumbsUp, MessageSquare, Plus, ChevronDown, Trash2, Droplet, Lightbulb, Users, AlertTriangle, Zap, } from "lucide-react";
import clsx from "clsx";
const FILTER_TABS = ["Near Me", "My Issues", "Needs Attention", "Resolved", "High Priority"];
const ISSUES = [
    { id: "1", category: "Garbage", priority: "High Priority", priorityLevel: "high", time: "2h ago", title: "Overflowing bin on High St", description: "Main waste collection point hasn't been cleared for 3 days. Foul smell spreading to nearby residential units.", workflow: 0, workflowLabels: ["Reported", "Verified", "Assigned", "In Progress", "Resolved"], activeLabel: "Reported", comments: 12, supports: 45 },
    { id: "2", category: "Pothole", priority: "Medium", priorityLevel: "medium", time: "5h ago", title: "Deep pothole near Junction 4", description: "Hazardous pothole causing traffic slowdowns and extreme risk to two-wheelers especially during nights.", workflow: 1, workflowLabels: ["Reported", "Verified", "Assigned", "In Progress", "Resolved"], activeLabel: "Verified", comments: 8, supports: 102 },
    { id: "3", category: "Water", priority: "Urgent", priorityLevel: "urgent", time: "1d ago", title: "Main pipe burst at Sector 4", description: "Significant water wastage on the road. Authorities have started excavation but supply is cut off.", workflow: 3, workflowLabels: ["Reported", "Verified", "Assigned", "In Progress", "Resolved"], activeLabel: "In Progress", comments: 24, supports: 256 },
    { id: "4", category: "Streetlight", priority: "Low", priorityLevel: "low", time: "2d ago", title: "Faulty lamp post #452", description: "No light for the past week in the park lane area. Security concern for residents.", workflow: 2, workflowLabels: ["Reported", "Verified", "Assigned", "In Progress", "Resolved"], activeLabel: "Assigned", comments: 3, supports: 18 },
    { id: "5", category: "Drainage", priority: "High", priorityLevel: "high", time: "3h ago", title: "Clogged drain on Market Road", description: "Water stagnant after minor rains yesterday. Affecting foot traffic to the local shops.", workflow: 0, workflowLabels: ["Reported", "Verified", "Assigned", "In Progress", "Resolved"], activeLabel: "Reported", comments: 15, supports: 89 },
    { id: "6", category: "Garbage", priority: "Medium", priorityLevel: "medium", time: "6h ago", title: "Illegal dumping near canal", description: "Construction debris being dumped regularly after midnight. Needs strict patrolling.", workflow: 1, workflowLabels: ["Reported", "Verified", "Assigned", "In Progress", "Resolved"], activeLabel: "Verified", comments: 6, supports: 32 },
    { id: "7", category: "Public Park", priority: "Medium", priorityLevel: "medium", time: "12h ago", title: "Broken benches in Central Park", description: "Three benches near the play area have broken slats. Dangerous for children and elderly.", workflow: 2, workflowLabels: ["Reported", "Verified", "Assigned", "In Progress", "Resolved"], activeLabel: "Assigned", comments: 4, supports: 21 },
    { id: "8", category: "Sidewalk", priority: "High", priorityLevel: "high", time: "1d ago", title: "Encroachment on Sector 2 Path", description: "Temporary stalls have blocked the entire walking path. Pedestrians forced to walk on road.", workflow: 0, workflowLabels: ["Reported", "Verified", "Assigned", "In Progress", "Resolved"], activeLabel: "Reported", comments: 31, supports: 142 },
    { id: "9", category: "Traffic", priority: "Medium", priorityLevel: "medium", time: "2d ago", title: "Malfunctioning traffic signal", description: "Signal at Nehru Crossing is stuck on red for North-bound traffic. Chaos during peak hours.", workflow: 3, workflowLabels: ["Reported", "Verified", "Assigned", "In Progress", "Resolved"], activeLabel: "In Progress", comments: 19, supports: 88 },
    { id: "10", category: "Sanitation", priority: "Low", priorityLevel: "low", time: "3d ago", title: "Litter near Metro Exit", description: "High volume of food wrappers and plastic bottles. Need more bins in the vicinity.", workflow: 1, workflowLabels: ["Reported", "Verified", "Assigned", "In Progress", "Resolved"], activeLabel: "Verified", comments: 7, supports: 29 },
    { id: "11", category: "Stray Animals", priority: "Medium", priorityLevel: "medium", time: "4d ago", title: "Aggressive stray pack near School", description: "Residents concerned for children's safety during morning hours. Requesting relocation/vaccination.", workflow: 1, workflowLabels: ["Reported", "Verified", "Assigned", "In Progress", "Resolved"], activeLabel: "Verified", comments: 14, supports: 77 },
    { id: "12", category: "Security", priority: "Critical", priorityLevel: "critical", time: "5d ago", title: "Broken gate at Community Center", description: "Main gate hinge broken. Center is open to unauthorized access during night time.", workflow: 4, workflowLabels: ["Reported", "Verified", "Assigned", "In Progress", "Resolved"], activeLabel: "Resolved", comments: 2, supports: 45 },
];
const priorityColors = {
    critical: "bg-[var(--color-error-bg)] text-[var(--color-error)]",
    urgent: "bg-[var(--color-error-bg)] text-[var(--color-error)]",
    high: "bg-[var(--color-error-bg)] text-[var(--color-error)]",
    medium: "bg-[var(--color-bg-subtle)] text-[var(--color-text-secondary)]",
    low: "bg-[var(--color-bg-subtle)] text-[var(--color-text-secondary)]",
};
function WorkflowTracker({ issue }) {
    return (_jsxs("div", { children: [_jsxs("div", { className: "relative flex justify-between items-center mb-2 px-2", children: [_jsx("div", { className: "absolute top-1/2 left-0 right-0 h-[2px] bg-[var(--color-border)] -translate-y-1/2 z-0" }), issue.workflowLabels.map((label, i) => (_jsx("div", { className: clsx("w-2 h-2 rounded-full z-[1] relative", i <= issue.workflow ? "bg-[var(--color-brand)]" : "bg-[var(--color-border)]", i === issue.workflow && "shadow-[0_0_0_4px_rgba(163,22,33,0.15)]") }, label)))] }), _jsx("div", { className: "flex justify-between text-[10px] text-[var(--color-text-secondary)] uppercase font-bold", children: issue.workflowLabels.map((label, i) => (_jsx("span", { className: i === issue.workflow ? "text-[var(--color-brand)]" : "", children: i === issue.workflow ? label : "" }, label))) })] }));
}
const categoryIcons = {
    Garbage: Trash2, Pothole: AlertTriangle, Water: Droplet,
    Streetlight: Lightbulb, Drainage: Droplet, "Public Park": Lightbulb,
    Sidewalk: Users, Traffic: Zap, Sanitation: Trash2,
    "Stray Animals": Users, Security: AlertTriangle,
};
export default function IssuesPage() {
    const [activeTab, setActiveTab] = useState("Near Me");
    const [supported, setSupported] = useState(new Set());
    function toggleSupport(id) {
        setSupported((prev) => {
            const next = new Set(prev);
            if (next.has(id))
                next.delete(id);
            else
                next.add(id);
            return next;
        });
    }
    return (_jsxs("div", { className: "flex-1 flex gap-8 p-8 min-h-0", children: [_jsxs("div", { className: "flex-1 min-w-0", children: [_jsxs("div", { className: "flex justify-between items-start mb-8", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-[var(--text-heading)] font-bold text-[var(--color-text-primary)] mb-1", children: "Issues" }), _jsx("p", { className: "text-sm text-[var(--color-text-secondary)]", children: "Join 12,402 citizens in monitoring and fixing ward problems." })] }), _jsxs(Link, { to: "/issues/new", className: "inline-flex items-center gap-2 px-6 py-3 bg-[var(--color-brand)] text-[var(--color-text-inverse)] rounded-xl font-bold shadow-md hover:shadow-lg transition-all active:scale-95", children: [_jsx(Plus, { size: 18 }), "Report Issue"] })] }), _jsxs("div", { className: "space-y-4 mb-8", children: [_jsx("div", { className: "flex gap-2 overflow-x-auto no-scrollbar pb-1", children: FILTER_TABS.map((tab) => (_jsx("button", { onClick: () => setActiveTab(tab), className: clsx("px-5 py-2 rounded-full text-sm font-bold whitespace-nowrap shadow-sm transition-colors", activeTab === tab
                                        ? "bg-[var(--color-brand)] text-[var(--color-text-inverse)]"
                                        : "bg-[var(--color-bg-surface)] border border-[var(--color-border)] text-[var(--color-text-secondary)] hover:bg-[var(--color-bg-subtle)]"), children: tab }, tab))) }), _jsxs("div", { className: "flex flex-wrap gap-3 items-center", children: [["Ward: All South", "Distance: 5km", "Category: All", "Status: Active", "Priority: Any"].map((f) => (_jsxs("div", { className: "flex items-center gap-1.5 px-3 py-1.5 bg-[var(--color-bg-subtle)] border border-[var(--color-border)] rounded-lg text-xs cursor-pointer hover:bg-[var(--color-bg-muted)] transition-colors", children: [_jsxs("span", { className: "text-[var(--color-text-secondary)]", children: [f.split(":")[0], ":"] }), _jsx("span", { className: "font-bold text-[var(--color-text-primary)]", children: f.split(":")[1] }), _jsx(ChevronDown, { size: 12, className: "text-[var(--color-text-secondary)]" })] }, f))), _jsx("button", { className: "text-[var(--color-brand)] text-xs font-bold ml-auto hover:underline", children: "Clear all filters" })] })] }), _jsx("div", { className: "grid grid-cols-1 xl:grid-cols-2 2xl:grid-cols-3 gap-6", children: ISSUES.map((issue) => {
                            const isSupported = supported.has(issue.id);
                            return (_jsxs("article", { className: "bg-[var(--color-bg-surface)] border border-[var(--color-border)] rounded-xl p-5 hover:shadow-md transition-shadow group", children: [_jsxs("div", { className: "flex justify-between items-start mb-4", children: [_jsxs("div", { className: "flex gap-2 items-center", children: [_jsxs("span", { className: "flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider text-white bg-[var(--color-brand)]", children: [(() => {
                                                                const CatIcon = categoryIcons[issue.category] || AlertTriangle;
                                                                return _jsx(CatIcon, { size: 12 });
                                                            })(), issue.category] }), _jsx("span", { className: clsx("px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider", priorityColors[issue.priorityLevel]), children: issue.priority })] }), _jsx("span", { className: "text-[11px] text-[var(--color-text-secondary)]", children: issue.time })] }), _jsx("h3", { className: "text-lg font-bold text-[var(--color-text-primary)] mb-2 group-hover:text-[var(--color-brand)] transition-colors cursor-pointer", children: issue.title }), _jsx("p", { className: "text-sm text-[var(--color-text-secondary)] mb-6 line-clamp-2", children: issue.description }), _jsx("div", { className: "mb-6", children: _jsx(WorkflowTracker, { issue: issue }) }), _jsxs("div", { className: "flex items-center justify-between pt-4 border-t border-[var(--color-border)]", children: [_jsxs("div", { className: "flex gap-4", children: [_jsxs("div", { className: "flex items-center gap-1.5 text-[var(--color-text-secondary)]", children: [_jsx(MessageSquare, { size: 16 }), _jsx("span", { className: "text-xs font-bold", children: issue.comments })] }), _jsxs("div", { className: "flex items-center gap-1.5 text-[var(--color-text-secondary)]", children: [_jsx(ThumbsUp, { size: 16 }), _jsx("span", { className: "text-xs font-bold", children: issue.supports + (isSupported ? 1 : 0) })] })] }), _jsxs("button", { onClick: () => toggleSupport(issue.id), className: clsx("px-4 py-1.5 rounded-full text-xs font-bold transition-all flex items-center gap-1", isSupported
                                                    ? "bg-[var(--color-bg-subtle)] text-[var(--color-text-secondary)] border border-[var(--color-border)]"
                                                    : "bg-[var(--color-brand)] text-[var(--color-text-inverse)] hover:opacity-90"), children: [_jsx(ThumbsUp, { size: 14, fill: isSupported ? "currentColor" : "none" }), isSupported ? "Supported" : "Support"] })] })] }, issue.id));
                        }) }), _jsx("div", { className: "mt-12 text-center", children: _jsx("button", { className: "px-8 py-3 bg-[var(--color-bg-muted)] border border-[var(--color-border)] text-[var(--color-text-primary)] rounded-xl font-bold hover:bg-[var(--color-bg-subtle)] transition-colors", children: "Load More Issues" }) })] }), _jsxs("aside", { className: "w-80 shrink-0 hidden lg:flex flex-col gap-6", children: [_jsxs("section", { className: "bg-[var(--color-bg-surface)] border border-[var(--color-border)] rounded-xl p-6", children: [_jsx("h2", { className: "font-bold text-[var(--color-text-primary)] mb-4", children: "Ward Snapshot" }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex justify-between items-center", children: [_jsx("span", { className: "text-sm text-[var(--color-text-secondary)]", children: "Open Issues" }), _jsx("span", { className: "text-lg font-bold text-[var(--color-brand)]", children: "124" })] }), _jsxs("div", { className: "flex justify-between items-center", children: [_jsx("span", { className: "text-sm text-[var(--color-text-secondary)]", children: "Resolved this week" }), _jsx("span", { className: "text-lg font-bold text-[var(--color-success)]", children: "42" })] }), _jsxs("div", { className: "flex justify-between items-center", children: [_jsx("span", { className: "text-sm text-[var(--color-text-secondary)]", children: "Avg. Resolution Time" }), _jsx("span", { className: "text-lg font-bold text-[var(--color-text-primary)]", children: "3 days" })] }), _jsxs("div", { className: "pt-4 mt-4 border-t border-[var(--color-border)]", children: [_jsx("div", { className: "h-2 w-full bg-[var(--color-bg-subtle)] rounded-full overflow-hidden", children: _jsx("div", { className: "h-full bg-[var(--color-brand)] rounded-full", style: { width: "65%" } }) }), _jsx("p", { className: "text-[10px] text-[var(--color-text-secondary)] mt-2", children: "65% of monthly goal reached" })] })] })] }), _jsxs("section", { className: "bg-[var(--color-bg-surface)] border border-[var(--color-border)] rounded-xl p-6", children: [_jsx("h2", { className: "font-bold text-[var(--color-text-primary)] mb-4", children: "Trending Categories" }), _jsx("div", { className: "space-y-3", children: [
                                    { icon: Trash2, label: "Waste Management", count: 42 },
                                    { icon: Droplet, label: "Water Supply", count: 28 },
                                    { icon: Zap, label: "Roads & Traffic", count: 24 },
                                ].map((cat) => (_jsxs("div", { className: "flex items-center justify-between group cursor-pointer", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx(cat.icon, { size: 18, className: "text-[var(--color-text-secondary)]" }), _jsx("span", { className: "text-sm text-[var(--color-text-primary)]", children: cat.label })] }), _jsx("span", { className: "text-xs font-bold bg-[var(--color-bg-subtle)] px-2 py-0.5 rounded text-[var(--color-text-secondary)] group-hover:bg-[var(--color-brand)] group-hover:text-white transition-colors", children: cat.count })] }, cat.label))) })] }), _jsxs("section", { className: "bg-[var(--color-bg-surface)] border border-[var(--color-border)] rounded-xl p-6", children: [_jsx("h2", { className: "font-bold text-[var(--color-text-primary)] mb-4", children: "Community Champions" }), _jsx("div", { className: "space-y-4", children: [
                                    { initials: "RK", name: "Rahul Kapoor", detail: "8 issues resolved this month", badge: "verified" },
                                    { initials: "MS", name: "Meera Singh", detail: "142 supports provided", badge: "star" },
                                    { initials: "AS", name: "Amit Sharma", detail: "Active in Sector 4 Discussions", badge: null },
                                ].map((c) => (_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "w-8 h-8 rounded-full bg-[var(--color-bg-subtle)] flex items-center justify-center font-bold text-xs text-[var(--color-text-primary)]", children: c.initials }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("p", { className: "text-sm font-bold leading-tight text-[var(--color-text-primary)]", children: c.name }), _jsx("p", { className: "text-[10px] text-[var(--color-text-secondary)]", children: c.detail })] })] }, c.name))) }), _jsx("button", { className: "w-full mt-6 text-xs font-bold text-[var(--color-brand)] hover:underline", children: "View Leaderboard" })] })] })] }));
}
