import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { Link } from "react-router-dom";
import { Plus, Vote, MessageSquare, Share2, ChevronRight, TrendingUp, Clock, AlertTriangle } from "lucide-react";
import clsx from "clsx";
const FILTER_TABS = ["Open", "Closed", "My Polls", "Following", "Needs Your Vote", "Near Me"];
const POLLS = [
    {
        id: "1", featured: true, category: "High Priority", timeLeft: "2 days remaining",
        question: 'Should Ward 12 implement "No Car Sundays" on the Central Corridor?',
        description: "This proposal aims to reduce local carbon emissions and promote pedestrian activity. The pilot would run for 6 months between 8 AM and 4 PM.",
        options: [
            { label: "Yes, implement it", pct: 64, primary: true },
            { label: "No, maintain current traffic", pct: 36, primary: false },
        ],
        votes: "12,402", comments: 482,
    },
    { id: "2", featured: false, badge: "Environment", badgeClass: "bg-[var(--color-brand)]", timeLeft: "5d", question: "Increase funding for Ward 12 Community Gardens?", pct: 82, votes: "4.1k" },
    { id: "3", featured: false, badge: "Infrastructure", badgeClass: "bg-[var(--color-text-secondary)]", timeLeft: "12h", question: "Upgrade Street Lighting on North Avenue?", pct: 45, votes: "2.8k" },
    { id: "4", featured: false, badge: "Policy", badgeClass: "bg-[var(--color-brand)]", timeLeft: "1w", question: "Mandatory Solar Panels for New Developments?", pct: 58, votes: "9.2k" },
    { id: "5", featured: false, badge: "Services", badgeClass: "bg-[var(--color-brand)]", timeLeft: "2d", question: "Expand Public Library Weekend Hours?", pct: 91, votes: "1.5k" },
];
export default function PollsPage() {
    const [activeTab, setActiveTab] = useState("Open");
    return (_jsxs("div", { className: "flex-1 flex min-h-0", children: [_jsxs("div", { className: "flex-1 p-8 space-y-6 border-r border-[var(--color-border)] overflow-y-auto", children: [_jsxs("div", { className: "flex items-end justify-between", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-[var(--text-display)] font-bold text-[var(--color-text-primary)]", children: "Polls" }), _jsx("p", { className: "text-sm text-[var(--color-text-secondary)] max-w-xl", children: "Vote on civic decisions that matter to your community. Your voice directly influences policy and administrative actions." })] }), _jsxs(Link, { to: "/polls/new", className: "px-8 py-3 bg-[var(--color-brand)] text-[var(--color-text-inverse)] font-bold rounded-full flex items-center gap-2 hover:opacity-90 transition-all shadow-md", children: [_jsx(Plus, { size: 18 }), "Create Poll"] })] }), _jsxs("div", { className: "flex flex-col gap-4", children: [_jsx("div", { className: "flex items-center gap-2 overflow-x-auto pb-2 no-scrollbar", children: FILTER_TABS.map((tab) => (_jsxs("button", { onClick: () => setActiveTab(tab), className: clsx("px-4 py-2 rounded-full text-sm font-bold whitespace-nowrap transition-colors", activeTab === tab
                                        ? "bg-[var(--color-brand)] text-[var(--color-text-inverse)]"
                                        : "bg-[var(--color-bg-subtle)] text-[var(--color-text-secondary)] hover:bg-[var(--color-bg-muted)]"), children: [tab === "Needs Your Vote" && _jsx(AlertTriangle, { size: 14, className: "inline mr-1" }), tab === "Near Me" && _jsx(Clock, { size: 14, className: "inline mr-1" }), tab] }, tab))) }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("select", { className: "bg-[var(--color-bg-surface)] border border-[var(--color-border)] rounded-full px-4 py-1.5 text-sm text-[var(--color-text-secondary)] focus:ring-[var(--color-brand)] outline-none min-w-[140px]", children: _jsx("option", { children: "Gov Level" }) }), _jsx("select", { className: "bg-[var(--color-bg-surface)] border border-[var(--color-border)] rounded-full px-4 py-1.5 text-sm text-[var(--color-text-secondary)] focus:ring-[var(--color-brand)] outline-none min-w-[140px]", children: _jsx("option", { children: "Ward 12" }) }), _jsx("select", { className: "bg-[var(--color-bg-surface)] border border-[var(--color-border)] rounded-full px-4 py-1.5 text-sm text-[var(--color-text-secondary)] focus:ring-[var(--color-brand)] outline-none min-w-[140px]", children: _jsx("option", { children: "Category" }) }), _jsx("div", { className: "ml-auto flex items-center gap-2 text-[var(--color-text-secondary)] text-xs", children: _jsx("span", { children: "Sorted by: Recent" }) })] })] }), _jsx("div", { className: "grid grid-cols-1 xl:grid-cols-2 gap-6", children: POLLS.map((poll) => {
                            if (poll.featured) {
                                return (_jsxs("div", { className: "group bg-[var(--color-bg-surface)] border border-[var(--color-border)] p-6 rounded-xl hover:shadow-xl transition-all duration-300 xl:col-span-2", children: [_jsxs("div", { className: "flex items-start justify-between mb-4", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("span", { className: "bg-[var(--color-brand-light)] text-[var(--color-brand)] px-3 py-1 rounded-full text-[11px] font-bold uppercase tracking-wider", children: poll.category }), _jsxs("span", { className: "text-[var(--color-text-secondary)] text-xs flex items-center gap-1", children: [_jsx(Clock, { size: 14 }), poll.timeLeft] })] }), _jsx("button", { className: "text-[var(--color-text-secondary)] hover:text-[var(--color-brand)] transition-colors", children: "\u2022\u2022\u2022" })] }), _jsx("h3", { className: "text-xl font-bold text-[var(--color-text-primary)] mb-3 group-hover:text-[var(--color-brand)] transition-colors", children: poll.question }), _jsx("p", { className: "text-sm text-[var(--color-text-secondary)] mb-6 line-clamp-2", children: poll.description }), _jsx("div", { className: "space-y-4 mb-6", children: poll.options.map((opt) => (_jsxs("div", { className: "space-y-2", children: [_jsxs("div", { className: "flex justify-between text-sm", children: [_jsx("span", { className: "font-bold text-[var(--color-text-primary)]", children: opt.label }), _jsxs("span", { className: opt.primary ? "text-[var(--color-brand)] font-bold" : "text-[var(--color-text-secondary)]", children: [opt.pct, "%"] })] }), _jsx("div", { className: "h-3 w-full bg-[var(--color-bg-subtle)] rounded-full overflow-hidden", children: _jsx("div", { className: clsx("h-full rounded-full", opt.primary ? "bg-[var(--color-brand)]" : "bg-[var(--color-text-secondary)]"), style: { width: `${opt.pct}%` } }) })] }, opt.label))) }), _jsxs("div", { className: "flex items-center justify-between pt-6 border-t border-[var(--color-border)]", children: [_jsxs("div", { className: "flex items-center gap-4 text-sm text-[var(--color-text-secondary)]", children: [_jsxs("span", { className: "flex items-center gap-1", children: [_jsx(Vote, { size: 16 }), " ", poll.votes, " votes"] }), _jsxs("span", { className: "flex items-center gap-1", children: [_jsx(MessageSquare, { size: 16 }), " ", poll.comments, " comments"] })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("button", { className: "px-6 py-2 bg-[var(--color-brand)] text-[var(--color-text-inverse)] font-bold rounded-full hover:scale-105 transition-transform text-sm", children: "Vote Now" }), _jsx("button", { className: "p-2 border border-[var(--color-border)] rounded-full text-[var(--color-text-secondary)] hover:bg-[var(--color-bg-subtle)]", children: _jsx(Share2, { size: 16 }) })] })] })] }, poll.id));
                            }
                            return (_jsxs("div", { className: "bg-[var(--color-bg-surface)] border border-[var(--color-border)] p-6 rounded-xl hover:border-[var(--color-brand)] transition-colors flex flex-col", children: [_jsxs("div", { className: "flex items-center gap-2 mb-4", children: [_jsx("span", { className: clsx("text-white px-2 py-0.5 rounded-full text-[10px] uppercase font-bold tracking-tight", poll.badgeClass), children: poll.badge }), _jsxs("span", { className: "text-[var(--color-text-secondary)] text-[11px] ml-auto", children: [poll.timeLeft, " left"] })] }), _jsx("h4", { className: "text-lg font-bold text-[var(--color-text-primary)] mb-4 line-clamp-2", children: poll.question }), _jsxs("div", { className: "mt-auto space-y-4", children: [_jsx("div", { className: "h-2 w-full bg-[var(--color-bg-subtle)] rounded-full overflow-hidden", children: _jsx("div", { className: "h-full bg-[var(--color-brand)] opacity-80 rounded-full", style: { width: `${poll.pct}%` } }) }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("span", { className: "text-xs text-[var(--color-text-secondary)]", children: [poll.votes, " votes"] }), _jsxs("button", { className: "text-[var(--color-brand)] font-bold text-xs flex items-center gap-1 hover:underline", children: ["Vote ", _jsx(ChevronRight, { size: 14 })] })] })] })] }, poll.id));
                        }) })] }), _jsxs("aside", { className: "w-80 shrink-0 p-8 space-y-6 bg-[var(--color-bg-surface)] overflow-y-auto hidden lg:flex flex-col", children: [_jsxs("section", { children: [_jsx("h3", { className: "text-[11px] font-bold uppercase tracking-widest text-[var(--color-text-secondary)] mb-4", children: "Poll Statistics" }), _jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsxs("div", { className: "bg-[var(--color-brand-light)] p-4 rounded-lg border border-[var(--color-brand)]/20", children: [_jsx("p", { className: "text-[var(--color-brand)] text-[var(--text-display)] font-bold leading-tight", children: "42k" }), _jsx("p", { className: "text-[11px] text-[var(--color-text-secondary)]", children: "Total Votes" })] }), _jsxs("div", { className: "bg-[var(--color-bg-subtle)] p-4 rounded-lg border border-[var(--color-border)]", children: [_jsx("p", { className: "text-[var(--color-text-primary)] text-[var(--text-display)] font-bold leading-tight", children: "24" }), _jsx("p", { className: "text-[11px] text-[var(--color-text-secondary)]", children: "Active Polls" })] })] })] }), _jsxs("section", { children: [_jsx("h3", { className: "text-[11px] font-bold uppercase tracking-widest text-[var(--color-text-secondary)] mb-4", children: "Closing Soon" }), _jsx("div", { className: "space-y-3", children: [
                                    { title: "Metro Expansion Plan B", time: "Closing in 1h 45m", urgent: true },
                                    { title: "Youth Center Grant Allocation", time: "Closing in 4h", urgent: false },
                                ].map((item) => (_jsxs("div", { className: clsx("p-3 bg-[var(--color-bg-surface)] rounded-r-lg shadow-sm hover:shadow-md transition-shadow border-l-4", item.urgent ? "border-[var(--color-error)]" : "border-[var(--color-brand)]"), children: [_jsx("p", { className: "text-sm font-bold text-[var(--color-text-primary)] line-clamp-1", children: item.title }), _jsx("p", { className: clsx("text-[11px]", item.urgent ? "text-[var(--color-error)]" : "text-[var(--color-text-secondary)]"), children: item.time })] }, item.title))) })] }), _jsxs("section", { children: [_jsxs("div", { className: "flex items-center justify-between mb-4", children: [_jsx("h3", { className: "text-[11px] font-bold uppercase tracking-widest text-[var(--color-text-secondary)]", children: "Trending" }), _jsx(TrendingUp, { size: 16, className: "text-[var(--color-brand)]" })] }), _jsx("div", { className: "space-y-4", children: [
                                    { rank: "01", title: "Property Tax Rebates for Green Energy", trend: "+1.2k today", active: true },
                                    { rank: "02", title: "New Bypass Road Connectivity", trend: "+850 today", active: false },
                                ].map((item) => (_jsxs("div", { className: "flex gap-3", children: [_jsx("span", { className: clsx("font-bold text-lg", item.active ? "text-[var(--color-brand)]" : "text-[var(--color-border)]"), children: item.rank }), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-bold text-[var(--color-text-primary)] leading-snug", children: item.title }), _jsx("p", { className: "text-[11px] text-[var(--color-text-secondary)]", children: item.trend })] })] }, item.rank))) })] }), _jsxs("section", { children: [_jsx("h3", { className: "text-[11px] font-bold uppercase tracking-widest text-[var(--color-text-secondary)] mb-4", children: "Community Sentiment" }), _jsxs("div", { className: "relative h-48 bg-[var(--color-bg-surface)] border border-[var(--color-border)] rounded-lg overflow-hidden flex items-center justify-center p-4", children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-br from-[var(--color-brand)]/5 to-[var(--color-text-secondary)]/5" }), _jsxs("div", { className: "relative w-full h-full flex items-center justify-center", children: [_jsx("div", { className: "w-32 h-32 rounded-full border-2 border-dashed border-[var(--color-border)] flex items-center justify-center", children: _jsx("div", { className: "w-24 h-24 rounded-full border-2 border-[var(--color-brand)]/20 flex items-center justify-center", children: _jsx("div", { className: "w-16 h-16 rounded-full bg-[var(--color-brand)]/10 animate-pulse" }) }) }), ["Urban Dev", "Greenery", "Safety", "Tech"].map((label, i) => {
                                                const positions = [
                                                    "top-0 left-1/2 -translate-x-1/2",
                                                    "bottom-0 left-1/2 -translate-x-1/2",
                                                    "left-0 top-1/2 -translate-y-1/2",
                                                    "right-0 top-1/2 -translate-y-1/2",
                                                ];
                                                return (_jsx("span", { className: clsx("absolute bg-[var(--color-bg-surface)] px-2 py-1 border border-[var(--color-border)] rounded text-[11px] text-[var(--color-text-secondary)]", positions[i]), children: label }, label));
                                            })] })] }), _jsx("p", { className: "text-[11px] text-[var(--color-text-secondary)] text-center px-4 italic mt-3", children: "Insights gathered from last 30 days of voting activity." })] })] })] }));
}
