import re
import uuid

def process_file(filepath):
    with open(filepath, 'r') as f:
        content = f.read()

    # Find all UUID-like strings in the file that look like 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
    uuid_pattern = r'[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}'
    found_uuids = set(re.findall(uuid_pattern, content))
    
    # We want to keep the dummy ones (1111... 2222...) for easy identification,
    # or the user is asking to NOT use them at all!
    # "give a proper id, not like this: 5555555-5555-5555-5555-555555555555, use springboot identity strategy"
    # Actually, they want random proper UUIDs generated by java.util.UUID!
    
    mapping = {}
    for old_uuid in found_uuids:
        # Check if it's one of our repeating pattern ones
        if old_uuid.startswith(old_uuid[0]*8 + '-'):
             mapping[old_uuid] = str(uuid.uuid4())
             
    # Replace in file
    for old, new in mapping.items():
        content = content.replace(old, new)
        
    with open(filepath, 'w') as f:
        f.write(content)
        
    return mapping

print("Testing script execution")
